### ISSUE TITLE
Pip error: Protein embeddings 

### ISSUE THREAD

**Issue by btredcup** [dimiboeckaerts/PhageRBPdetection#1]
Hi, 

I am using Google Colab to run RBPdetect_protein_embeddings.ipynb but getting the below error when I try to run the first step.
The command:
````# Kaggle
!pip install bio_embeddings==0.2.2```


The error:
````ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
torchvision 0.12.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.
torchtext 0.12.0 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.
torchaudio 0.11.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible````

Any help would be appreciated. 
Thanks for the great tool and paper, looking forward to using this on some phage genomes.

**Comment by dimiboeckaerts** [comment]
Hi! Thanks for reaching out. 

In my experience, you can safely ignore the pip's dependency resolver error, as long as it is mentioned below the error that all packages were installed successfully: `Successfully installed xxx` (among which bio-embeddings-xxx). You can try and compute some embeddings to see if the package works. I will clarify this in the notebook as well.

If you have any more comments or questions, feel free to reach out!

Dimi
