### ISSUE TITLE
Tensor size issue.

### ISSUE THREAD

**Issue by J-JEMINA** [dimiboeckaerts/PhageRBPdetection#5]
Hey!
So as per instruction, I am trying to run the Protein embeddings notebook to generate the embeddings file. My input fasta file is a Complete genome of E.coli phage genome of size 108485bp. I don't know what I am missing but when I run it in google colab I get this error.

The expanded size of the tensor (108485) must match the existing size (40000) at non-singleton dimension 1.  Target sizes: [1, 108485].  Tensor sizes: [1, 40000]. This most likely means that you don't have enough GPU RAM to embed a protein this long.

I am really new to all of this and trying to follow the instructions given. So any help would be appreciated @dimiboeckaerts .

Thank you!

**Comment by dimiboeckaerts** [comment]
Hi Jemina! Thanks for your interest in using PhageRBPdetection! OK so to understand correctly: the fasta file you are using is simply one full genome (DNA sequence)? That indeed will not work, you need the protein sequences for each of the CDSs in the genome. Now, the ProtTrans model will try to encode the full genome into a vector, but that's a way too long sequence for it to process, so you get that error.

One way to get protein sequences from a genome is to run PHANOTATE (its also a Python file that you can run locally on your laptop) and then translate each CDS to protein sequences using BioPython. Hope this helps!

**Comment by J-JEMINA** [comment]
I ran phanotate separately, processed the output and the whole genome using biopython like you said to create a singular fasta file with all the cds translated to protein sequence kinda in like this

>
...
...
AAseq1
...

>
...
...
AAseq2
...

And so on...

I just want to know am i doing this right? Any kind of help would be appreciated!

Thank you!

**Comment by dimiboeckaerts** [comment]
Yes indeed, if you have a fasta file with protein sequences in it, it should work. The format is:
>protein_name1
SEQUENCE1
>protein_name2
SEQUENCE2
...

There's also an example of it in the GitHub repo :)
